# frozen_string_literal: true
source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'erubis'
gem 'rack'
gem 'minitest'
gem 'minitest-reporters'

group :production do
  gem "puma"
end

group :development do
  gem 'pry'
  gem 'rubocop'
end
